{% set name = "pyiron_ontology" %}
{% set version = "0.0.2" %}
{% set sha256 = "cdc5630c4e60d4a063211d9a0665aa56a1ff2ffe0c4a8a084d4a76c7b46f71d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_ontology-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - projecttoml.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - openjdk
    - owlready2
    - pandas
    - pint
    - pyiron_atomistics

test:
  imports:
    - pyiron_ontology
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_ontology
  summary: pyiron_ontology - module extension to pyiron.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
     pyiron_ontology provides owlready2-based ontologies and tools to leverage them for pyiron projects.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - pyiron-runner
    - liamhuber
